apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: odoo
  namespace: odoo
spec:
  template:
    spec:
      containers:
        - image: odoo:13.0
          env:
          - name: HOST
            value: "localhost"
