#!/bin/bash

export KNATIVE_VERSION="0.13.0"

export ISTIO_VERSION="1.4.6"

export PROJECT_ID="nurlanfpremiumproject"

export CLUSTER_NAME="knative-1"

export CLUSTER_REGION="us-central1"

export CLUSTER_ZONE="${CLUSTER_REGION}-c"

export CLUSTER_START_NODE_SIZE=3

export CLUSTER_MAX_NODE_SIZE=10

export CLUSTER_NODE_MACHINE_TYPE="n1-standard-4"

export CLUSTER_MASTER_VERSION="latest"
